# Generated by Django 4.1.2 on 2022-11-30 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0002_rentuser_groups_rentuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='rentuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='rentuser',
            name='user_permissions',
        ),
    ]
