# Generated by Django 4.1.2 on 2022-11-30 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0003_remove_rentuser_groups_remove_rentuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
