# Generated by Django 4.1.2 on 2022-12-02 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0006_remove_rentuser_groups_remove_rentuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentuser',
            name='phone_number',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.CreateModel(
            name='HouseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_name', models.CharField(max_length=30)),
                ('house_location', models.CharField(max_length=20)),
                ('rent_per_month', models.CharField(max_length=10)),
                ('house_type', models.CharField(choices=[('BD', 'BedSitter'), ('OB', 'One Bedroom'), ('TB', 'Two Bedroom'), ('THD', 'Three Bedroom'), ('CM', 'Commercial'), ('GH', 'Guest House')], default='BedSitter', max_length=15)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
